# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 00:27
from __future__ import unicode_literals
from django.db import models, migrations

def load_quotes_from_sql():
    from quotsyProject.settings import PROJECT_DIR
    import os
    sql_statements = open(os.path.join(PROJECT_DIR,'apps/quotesy/sql/quotes.sql'), 'r').read()
    return sql_statements

class Migration(migrations.Migration):

    dependencies = [
        ('quotesy', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(load_quotes_from_sql()),
    ]
