var num1 = 3;
var num2 = 35.86;
var num3 = -42;
var num4 = 654;
var string1 = "This is the first string.";
var string2 = "This is string number two.";
var string3 = "This is the last string! Hooray!";
var boolean1=true;
var boolean2=false;
var undefinedVar;
console.log("The first number is small:", num1);
console.log("The second number is a decimal:", num2);
console.log("The third number is negative:", num3);
console.log("The fourth number is large:", num4);
console.log("Here's the first string:", string1);
console.log("Here's the second string:", string2);
console.log("Here's the third string:", string3);
console.log("First boolean variable, are you true?", boolean1);
console.log("Second boolean variable, are you true?", boolean2);
console.log("Can you print the undefined variable?", undefinedVar);
